Update configure script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,4 +1,3 @@
-#!/usr/bin/env bash
 # Anticonf (tm) script by Jeroen Ooms (2020)
 # This script will query 'pkg-config' for the required cflags and ldflags.
 # If pkg-config is unavailable or does not find the library, try setting
@@ -16,10 +15,10 @@ PKG_LIBS="-lprotobuf"
 PKG_CFLAGS=""
 
 # Use pkg-config if available
-if [ $(command -v pkg-config) ]; then
-  PKGCONFIG_CFLAGS=$(pkg-config --cflags --silence-errors ${PKG_CONFIG_NAME})
-  PKGCONFIG_LIBS=$(pkg-config --libs ${PKG_CONFIG_NAME})
-  PKGCONFIG_MODVERSION=$(pkg-config --modversion --silence-errors ${PKG_CONFIG_NAME})
+if [ `command -v pkg-config` ]; then
+  PKGCONFIG_CFLAGS=`pkg-config --cflags --silence-errors ${PKG_CONFIG_NAME}`
+  PKGCONFIG_LIBS=`pkg-config --libs ${PKG_CONFIG_NAME}`
+  PKGCONFIG_MODVERSION=`pkg-config --modversion --silence-errors ${PKG_CONFIG_NAME}`
 fi
 
 # Note that cflags may be empty in case of success
@@ -31,16 +30,14 @@ elif [ "$PKGCONFIG_CFLAGS" ] || [ "$PKGCONFIG_LIBS" ]; then
   echo "Found pkg-config cflags and libs!"
   PKG_CFLAGS=${PKGCONFIG_CFLAGS}
   PKG_LIBS=${PKGCONFIG_LIBS}
-elif [[ "$OSTYPE" == "darwin"* ]]; then
-  if [ $(command -v brew) ]; then
-    BREWDIR=$(brew --prefix)
+elif [ `uname` = "Darwin" ]; then
+  brew --version 2>/dev/null
+  if [ $? -eq 0 ]; then
+    BREWDIR=`brew --prefix`
   else
-    curl -sfL "https://jeroen.github.io/autobrew/$PKG_BREW_NAME" > $TMPDIR/autobrew
+    curl -sfL "https://autobrew.github.io/jeroen/$PKG_BREW_NAME" > $TMPDIR/autobrew
     source $TMPDIR/autobrew
   fi
-  PATH="$BREWDIR/opt/$PKG_BREW_NAME/bin:$PATH"
-  PKG_CFLAGS="-I$BREWDIR/opt/$PKG_BREW_NAME/include"
-  PKG_LIBS="-L$BREWDIR/opt/$PKG_BREW_NAME/lib $PKG_LIBS"
 fi
 
 # For debugging
@@ -48,12 +45,12 @@ echo "Using PKG_CFLAGS=$PKG_CFLAGS"
 echo "Using PKG_LIBS=$PKG_LIBS"
 
 # Find compiler
-CXX=$(${R_HOME}/bin/R CMD config CXX)
-CXXFLAGS=$(${R_HOME}/bin/R CMD config CXXFLAGS)
-CPPFLAGS=$(${R_HOME}/bin/R CMD config CPPFLAGS)
+CXX11=`${R_HOME}/bin/R CMD config CXX11`
+CXX11STD=`${R_HOME}/bin/R CMD config CXX11STD`
+CPPFLAGS=`${R_HOME}/bin/R CMD config CPPFLAGS`
 
 # Test configuration
-echo "#include $PKG_TEST_HEADER" | ${CXX} -E ${CPPFLAGS} ${PKG_CFLAGS} ${CXXFLAGS} -xc++ - >/dev/null 2>configure.log
+echo "#include $PKG_TEST_HEADER" | ${CXX11} ${CXX11STD} -E ${CPPFLAGS} ${PKG_CFLAGS} ${CXXFLAGS} -xc++ - >/dev/null 2>configure.log
 
 # Customize the error
 if [ $? -ne 0 ]; then
@@ -77,18 +74,18 @@ fi
 sed -e "s|@cflags@|$PKG_CFLAGS|" -e "s|@libs@|$PKG_LIBS|" src/Makevars.in > src/Makevars
 
 # Look for 'protoc' compiler
-if [ $(command -v protoc) ]; then
-  PROTOC_VERSION=$(protoc --version)
-  echo "Using ${PROTOC_VERSION} from $(command -v protoc)"
+if [ `command -v protoc` ]; then
+  PROTOC_VERSION=`protoc --version`
+  echo "Using ${PROTOC_VERSION} from `command -v protoc`"
 else
-  echo "Failed to run protoc."
+  echo "Failed to find protoc"
   echo "Please install the 'protobuf-compiler' package for your system."
   exit 1
 fi
 
-# Try to check if protoc version matches libproto
-if [[ $PROTOC_VERSION != *"$PKGCONFIG_MODVERSION"* ]]; then
-  echo "Warning: protoc version $PROTOC_VERSION might not match libproto version $PKGCONFIG_MODVERSION.";
+# Complicated POSIX shell method to test if one is substring of the other
+if [ "${PROTOC_VERSION#*$PKGCONFIG_MODVERSION}" = "$PROTOC_VERSION" ]; then
+  echo "Warning: protoc version $PROTOC_VERSION might not match libproto version $PKGCONFIG_MODVERSION."
 fi
 
 # Compile proto file
